"""
Django settings for consultorio project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import socket
import qrcode
import environ
import shutil
import sys, os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BUNDLE_DIR = BASE_DIR
if getattr(sys, 'frozen', False):
    BASE_DIR = Path(sys.executable).resolve().parent
    BUNDLE_DIR = Path(sys._MEIPASS)
print(BASE_DIR)

env_path = BASE_DIR / '.env'
if not env_path.is_file():
    shutil.copy(BUNDLE_DIR / '.env.example', env_path)

def resolve_path(env_value):
    path = Path(env_value)
    if path.is_absolute(): return path
    return BASE_DIR / path

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-75(gtt$ltn^brj0&u7*%7hiqm@)-&u6pxrnl7g#_j*bpfp2v3n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
# append local ip, works for the first network adapter, (virtual adapters may interfere)
LOCAL_IP = socket.gethostbyname(socket.gethostname()) 
#(lambda s: (s.connect(("8.8.8.8", 80)), s.getsockname()[0]))(socket.socket(socket.AF_INET, socket.SOCK_DGRAM))[1] works for linux but throws OSError with disabled network adapter
ALLOWED_HOSTS.append(LOCAL_IP)
qrimg = qrcode.make('http://'+LOCAL_IP+':8000')
qrimg.save(BUNDLE_DIR / "historia/static/qrip.png")


# Custom settings
env = environ.Env()
env.read_env('.env', parse_comments=True)

APP_FLAVOR = env('APP_FLAVOR') # Options: 'GENERAL', 'OPTICAL'
BACKUP_LOCATION = resolve_path(env('BACKUP_LOCATION')) # "C:\\backupsConsultorio\\"
DRIVE_FOLDER_ID = env('DRIVE_FOLDER_ID')
SHOW_GIT_VERSIONS = env.bool('SHOW_GIT_VERSIONS', default=False)
DATABASE = resolve_path(env('DATABASE'))
DAYS_LOCAL_FREQ = int(env('DAYS_LOCAL_FREQ'))
DAYS_ONLINE_FREQ = int(env('DAYS_ONLINE_FREQ'))
RESTORED_TRASH_PATH = resolve_path(env('RESTORED_TRASH_PATH'))

os.makedirs(DATABASE.parent, exist_ok=True)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'historia',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    #only for debug False, pyinstaller: --hidden-import=whitenoise --hidden-import=whitenoise.middleware
    #'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'consultorio.urls'

LOGIN_URL = '/admin/login/'
SESSION_COOKIE_AGE = 315360000
SESSION_SAVE_EVERY_REQUEST = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BUNDLE_DIR / 'historia' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'historia.backup.session_status',
                'historia.apps.flavor'
            ],
        },
    },
]

#WSGI_APPLICATION = 'consultorio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATABASE,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-AR'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'collectstatic'
#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = "files/"

MEDIA_ROOT = resolve_path(env('MEDIA_ROOT'))   # "media"  "C:\\mediaConsultorio"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
