# Generated by Django 5.1.4 on 2025-07-08 11:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['-modificado']},
        ),
        migrations.AddField(
            model_name='persona',
            name='afiliado',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='comentarios',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='persona',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='persona',
            name='localidad',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='persona',
            name='obraSocial',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('comentarios', models.TextField(blank=True, default='')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='historia.persona')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
