# Generated by Django 5.1.4 on 2025-07-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0002_alter_persona_options_persona_afiliado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='edad',
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
    ]
