# Generated by Django 5.2.4 on 2025-07-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0003_remove_persona_edad_alter_persona_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='afiliado2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='extras',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='obraSocial2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
