# Generated by Django 5.2.4 on 2025-08-10 22:25

import django.db.models.deletion
import historia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0004_persona_activo_persona_afiliado2_persona_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to=historia.models.directorio)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='historia.entrada')),
            ],
        ),
    ]
