# Generated by Django 5.1.4 on 2025-09-23 02:26

import django.db.models.deletion
import historia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0005_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='imagen',
            new_name='archivo',
        ),
        migrations.AddField(
            model_name='persona',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='persona',
            name='ocupacion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='persona',
            name='sangre',
            field=models.CharField(blank=True, choices=[('A+', 'A Positivo'), ('A-', 'A Negativo'), ('B+', 'B Positivo'), ('B-', 'B Negativo'), ('AB+', 'AB Positivo'), ('AB-', 'AB Negativo'), ('O+', 'O Positivo'), ('O-', 'O Negativo')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='', max_length=1),
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(null=True, upload_to=historia.models.directorio)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='historia.entrada')),
            ],
        ),
    ]
