# Generated by Django 5.1.4 on 2025-11-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0006_rename_imagen_imagen_archivo_persona_altura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='add',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entrada',
            name='akr',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entrada',
            name='antec_medicos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='antec_oculares',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='av_cc',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entrada',
            name='av_sc',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entrada',
            name='formula',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entrada',
            name='medicamentos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='motivo_consulta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='obs_generales',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='obs_segmento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='retinoscopia',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entrada',
            name='subjetivo',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
