# Generated by Django 5.1.4 on 2025-12-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0007_entrada_add_entrada_akr_entrada_antec_medicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='cc_uso',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entrada',
            name='queratometria',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
